- hosts: jenkins
  connection: local
  become: yes
  vars:
    jenkins_hostname: "127.0.0.1"
    java_packages: "java-1.8.0-openjdk"
  roles:
    - role: ansible-role-jenkins
    - role: ansible-role-nginx
    - role: ansible-role-zabbix-server
    - role: ansible-role-zabbix-javagateway
    - role: ansible-role-zabbix-agent
      become: true
