---
    - name: add group "tomcat"
      group: name=tomcat
      become: true

    - name: add user "tomcat"
      user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
      become: true
      become_method: sudo

    - name: create directory for Tomcat
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755

    - name: Download Tomcat
      get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.8/bin/apache-tomcat-8.5.8.tar.gz dest=/opt/apache-tomcat-8.5.8.tar.gz
      become: true

    - name: Extract Tomcat archive Custom
      unarchive:
         src: /opt/apache-tomcat-8.5.8.tar.gz
         dest: /opt/tomcat
         copy: no
         extra_opts: [--strip-components=1]

    - name: Set Tomcat Deployment Directory Permissions
      file: dest=/opt/tomcat state=directory owner=tomcat  group=tomcat  mode=0775
      become: true

    - name: Change ownership of Tomcat installation
      file: path=/opt/tomcat owner=tomcat group=tomcat state=directory recurse=yes
      become: true

    - name: Configure Tomcat users
      template: src=tomcat-users.xml dest=/opt/tomcat/conf/
      become: true

    - name: Configure Tomcat Remote access
      template: src=context.xml dest=/opt/tomcat/webapps/manager/META-INF
      become: true

    - name: Install Tomcat init script
      copy: src=tomcat-initscript.sh dest=/etc/systemd/system/tomcat.service mode=0755
      become: true

    - name: systemd daemon-reload
      shell: systemctl daemon-reload
      become: true

    - name: tomcat-8-start
      service: name=tomcat state=started enabled=yes
      become: true

    - name: wait for tomcat to start
      wait_for: port=8080
